In [ ]:
dataset = np.array([[1,2,3,4,5],[1,2,3,4,5]])
rows,columns = dataset.shape
ratio = 1.2
number_of_dimensions_to_be_added = int(np.ceil((ratio * np.sqrt(columns))**2))
print "%d irrelevant features are going to be added to the dataset" %(number_of_dimensions_to_be_added)

#randomly choose a feature from the dataset, ie choose number_of_dimensions_to_be_added features

#random features to pick
features = []
for i in range(number_of_dimensions_to_be_added):
    features.append(np.random.randint(0,columns))
    
print features    
    
#add irreleant features
for i,feature in enumerate(features):
    appending_features = np.random.choice(dataset[:,feature],rows)
    appending_features = appending_features.reshape(1,rows)
    dataset= np.insert(dataset,columns+i,appending_features,axis=1)
    print dataset

In [ ]:
data = np.array([[1,2,3,4,5],[1,3,3,4,5],[1,3,3,4,5],[1,3,3,4,5],[1,3,3,4,5]])

#data= np.insert(data,5,[8,2],axis=1)

appending_features = np.random.choice(data[:,1],5)
appending_features = appending_features.reshape(1,5)
print appending_features
data= np.insert(data,5,appending_features,axis=1)
print data


In [356]:
def Euclidean_distance(x,y):
    return np.sqrt(np.sum((x-y)**2))
    
    
def Calculate_distances(distance_matrix,datapoint,seen,dataset):
    
    rows,columns = distance_matrix.shape
    
    for i,value in enumerate(range(columns)):
        if (seen[0,i]):
            distance_matrix[datapoint][i] = distance_matrix[i][datapoint]      
        else:
            distance_matrix[datapoint][i] = distance(dataset[datapoint,:],dataset[i,:])
            
def Mahalanobis_distance(heads,point):
    
    rows,columns = heads.shape
    
    if (rows>1):
        covariance = np.cov(heads,rowvar=0)
        var = np.var(heads[:,0],ddof=1)
        #covarianceInverse = np.linalg.inv(covariance)
        covariancePsuedoInverse = np.linalg.pinv(covariance)
    
        meanHeads = np.mean(heads,axis=0)
        delta = point - meanHeads
        
        return np.sqrt(np.dot(np.dot(delta, covariancePsuedoInverse), np.transpose(delta)))
         
    else:
        return Euclidean_distance(heads,point)
            
            
def Calculate_heads(dataset,heads,seen,k):
    
    datasetRows,datasetColumns = dataset.shape
    
    for i,head in enumerate(arange(1,k)):
        
        max_distance = -inf
        
        for j,value in enumerate(seen[0]):
            if not value:
                point = np.reshape(dataset[j,:],(1,datasetColumns))
                distance = Mahalanobis_distance(heads,point)
                
                if distance > max_distance:
                                   max_distance = distance
                                   index = j
        
        seen[0][index] = True
        heads = np.insert(heads,i+1,dataset[index,:],axis=0)
    
    return heads
                                            

In [358]:

dataset = np.random.randint(0,1000,(200,20))
rows,columns = dataset.shape
seen = np.zeros((1,rows), dtype= bool)
k = 3

#Pick an arbitrary datapoint
randomIndex = np.random.randint(0,rows)
heads = np.reshape(dataset[randomIndex,:],(1,columns)) 
seen[0][randomIndex] = True

#print dataset
print heads.shape
#print seen

print heads

heads =Calculate_heads(dataset,heads,seen,k)

print heads

#print Mahalanobis_distance(dataset[0:150,:],heads)

#print heads 

#seen = seen.tolist()
#print seen[0][1]

#heads = np.insert(heads,1,heads,axis=0)
#print heads
       

(1, 20)
[[369 949 920 268 916 104 475 652 385 633 882  91 402 975   3  88 633 593
  151 633]]
[[369 949 920 268 916 104 475 652 385 633 882  91 402 975   3  88 633 593
  151 633]
 [168 259 532 964  22 868 698 138 418 285  62 801 954 405 839 769 152  69
  912 525]
 [835 395 292 379 918  94 319 647 350 900 977  23 140 273 224 478 923 181
  227 608]]


In [128]:

dataset = np.random.randint(0,10,(10,5))
cova = np.cov(dataset,rowvar=0)
var = np.var(dataset[:,0],ddof=1)
print cova
print var
print cova.dot(np.linalg.inv(cova))

x = dataset[1,:]
y = dataset[1,:]

x = x.reshape(1,5)
y = y.reshape(1,5)

print Mahalanobis_distance(dataset[0:8,:],y)
#print np.mean(dataset,axis=0)




[[  6.1          5.58888889  -1.77777778   3.64444444  -4.93333333]
 [  5.58888889  12.01111111  -1.66666667   4.73333333  -6.97777778]
 [ -1.77777778  -1.66666667   5.33333333   1.           3.33333333]
 [  3.64444444   4.73333333   1.           7.06666667  -1.86666667]
 [ -4.93333333  -6.97777778   3.33333333  -1.86666667   7.15555556]]
6.1
[[  1.00000000e+00   0.00000000e+00   0.00000000e+00   1.11022302e-16
   -4.44089210e-16]
 [  0.00000000e+00   1.00000000e+00   2.22044605e-16   6.66133815e-16
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   0.00000000e+00
    0.00000000e+00]
 [  0.00000000e+00   2.22044605e-16   1.11022302e-16   1.00000000e+00
    0.00000000e+00]
 [  4.44089210e-16   0.00000000e+00  -2.22044605e-16   0.00000000e+00
    1.00000000e+00]]
[[ 2.40843514]]


In [361]:
from sklearn.datasets import load_iris

print load_iris()

{'target_names': array(['setosa', 'versicolor', 'virginica'], 
      dtype='|S10'), 'data': array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.